<div class="row espaco-topo">

	
	<? if(isset($status)): ?>

		<div class="span12">
			<div class="alert <?= $alert ?> centro">
		 	 	<button type="button" class="close" data-dismiss="alert">&times;</button>
		  		<?= $status ?>
			</div>
		</div>

	<? endif ?>


	<form method="post" action="<?= URL ?>contato" class="well span8">
	  <div class="row">
			<div class="span3">
				<label>Nome</label>
				<input name="nome" type="text" class="span3" placeholder="Seu nome">
				<label>Email</label>
				<input name="email" type="text" class="span3" placeholder="Seu email">
				<label>Assunto</label>
				<input name="assunto" type="text" class="span3" placeholder="Assunto">
			</div>
			<div class="span5">
				<label>Mensagem</label>
				<textarea name="mensagem" id="message" class="input-xlarge span5" rows="8"></textarea>
			</div>
		
			<button type="submit" class="btn btn-warning pull-right">Enviar</button>
		</div>
	</form>

	<div class="well span3 pull-right">
		<strong>Lorem ipsum dolor sit. </strong><br/>
		Lorem ipsum. <br/>
		Tel.: (xx) xxxx-xxxx <br/>

	</div>
</div>