<div class="row">
	<div class="span6"> <!-- LADO ESQUERDO -->
	
		<?php include (LIB . "shortcuts.php"); ?>
		
	</div>

	<div class="span6"> <!-- LADO DIREITO -->
		
		



		<!-- LISTA -->

		<div class="widget widget-table action-table">

			<div class="widget-header">
				<i class="icon-shopping-cart"></i>
				<h3>Últimos Produtos</h3>
			</div> <!-- /widget-header -->

			<div class="widget-content">

				<table class="table table-striped table-bordered">
					<thead>
						<tr>
							<th>Titulo</th>
							<th>Produtos</th>
							<th class="td-actions">Ações</th>
						</tr>
					</thead>
					<tbody>
						
						<tr> <!-- Bloco do Produto -->
							<td>Produto</td>
							<td>Categoria</td>
							<td class="td-actions">
								<a title="editar" href="#" class="btn btn-small btn-success">
									<i class="btn-icon-only icon-pencil"></i>										
								</a>

								<a title="excluir" href="#" class="btn btn-small btn-danger">
									<i class="btn-icon-only icon-remove"></i>										
								</a>
							</td>
						</tr> <!-- Fim do Bloco do Produto -->

					</tbody>
				</table>

			</div> <!-- /widget-content -->

		</div> <!-- /widget -->

		<!-- FIM LISTA -->





	</div>
</div> <!-- row -->