<div class="titulo">
	<h1>Listar Usuários</h1>
</div>

<div class="segura-tabela">
	<table class="table table-striped table-bordered data-table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Nome</th>
				<th>login</th>
				<th class="td-actions">Ações</th>
			</tr>
		</thead>
		<tbody>

		<?php foreach ( $info as $i):
				extract($i) ?>

			<tr>
				<td><?= $id_developer ?></td>
				<td><?= $nome ?></td>
				<td><?= $login ?></td>
				<td class='td-actions'>

					<!-- EDITAR -->
					<a title='editar' href='<?= URL ?>admin/edit/usuarios/<?= $id_developer ?>' class='btn btn-small btn-success'>
						<i class='btn-icon-only icon-pencil'></i>
					</a>

					<!-- EXCLUIR -->
					<a id="delete<?= $id_developer ?>" title='excluir' data='<?= URL ?>admin/del/usuarios/<?= $id_developer ?>' onclick="del(this.id)" class='btn btn-small btn-danger'>
						<i class='btn-icon-only icon-remove'></i>
					</a>
				</td>
			</tr>

		<?php endforeach; ?>

		</tbody>
	</table>
</div>