<div class="titulo">
	<h1>Listar Contatos</h1>
</div>

<div class="segura-tabela">
	<table class="table table-striped table-bordered data-table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Data</th>
				<th>Nome</th>
				<th>Email</th>
				<th>Mensagem</th>
				<th class="td-actions">Ações</th>
			</tr>
		</thead>
		<tbody>

		<?php foreach ( $info as $i):
				extract($i) ?>

			<tr>
				<td><?= $id_contato ?></td>
				<td><?= date("d/m/Y - H:m:s", strtotime($data)) ?></td>
				<td><?= $nome ?></td>
				<td><?= $email ?></td>
				<td><?= $mensagem ?></td>

				<td class='td-actions'>

					<!-- EDITAR -->
					<a title='editar' href='<?= URL ?>admin/edit/contato/<?= $id_contato ?>' class='btn btn-small btn-success'>
						<i class='btn-icon-only icon-pencil'></i>
					</a>

					<!-- EXCLUIR -->
					<a id="delete<?= $id_contato ?>" title='excluir' data='<?= URL ?>admin/del/contato/<?= $id_contato ?>' onclick="del(this.id)" class='btn btn-small btn-danger'>
						<i class='btn-icon-only icon-remove'></i>
					</a>
				</td>
			</tr>

		<?php endforeach; ?>

		</tbody>
	</table>
</div>