<?php 
	global $start;
	if(isset($dados)) extract($dados);
?>

<div class="title">
	<h1><?= $action ?> Usuários</h1>
</div>

<div class="widget-form">
	<form method="post" action="<?= URL . 'admin/' . $start->_action ?>/usuarios/<?php if(isset($id)) echo $id; ?>" enctype="multipart/form-data">
		<div class="form-group">
		    <label for="nome">Nome</label>
		    <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome" value='<?php if(isset($nome)) echo $nome; ?>'>
		 </div>
		 <div class="form-group">
		    <label for="login">Login</label>
		    <input type="text" class="form-control" id="login" name="login" placeholder="login" value='<?php if(isset($login)) echo $login; ?>'>
		 </div>
		 <div class="form-group">
		    <label for="imagem">Imagem</label>
		    <input type="file" class="form-control" id="imagem" name="imagem">
		 </div>
		 <div class="form-group">
		    <label for="senha">Senha</label>
		    <input type="password" class="form-control" id="senha" name="senha" placeholder="<?= (isset($senha)) ? 'Nova senha' : 'Senha' ?>">
		 </div>
		 <div class="form-group">
		 	<button class="btn btn-success"><i class="icon icon-ok"></i> <?= (isset($id)) ? "Salvar" : "Adicionar" ?>
		 </div>
	</form>
</div>