<?php 
	global $start;
	if(isset($dados)) extract($dados);
?>


<div class="row">
	<div class="span6 offset3 form_edit"> 

		<div class="widget">
			<div class="widget-header">
				<i class="icon-lock"></i>
				<h3>Usuário</h3>
			</div> <!-- /widget-header -->

			<div class="widget-content">

				<?php if(isset($status)) echo "<div class='well well-large'><center>" . $status . "</center></div>"; ?>

			<!-- class="form-horizontal" -->
			<form method="post" action="<?= URL . 'admin/' . $start->_action ?>/usuarios/<?php if(isset($id)) echo $id; ?>" class="form-horizontal">

				<div class="control-group">
					<label class="control-label" for="nome">Nome</label>
					<div class="controls">
						<input type="text" id="nome" name="nome" placeholder="Nome" value='<?php if(isset($nome)) echo $nome; ?>'>
					</div>
				</div>


				<div class="control-group">
					<label class="control-label" for="login">Login</label>
					<div class="controls">
						<input type="text" id="login" name="login" placeholder="login" value='<?php if(isset($login)) echo $login; ?>'>
					</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="senha">Senha</label>
					<div class="controls">
						<input type="password" id="senha" name="senha" placeholder="<?= (isset($senha)) ? 'Nova senha' : 'Senha' ?>" value=''>
					</div>
				</div>

				<div class="control-group">
					<div class="controls">						
						<a href="<?= URL ?>admin/lista/usuarios" class="btn btn-default"><i class="icon icon-reply"></i> Voltar</a>
						<button class="btn btn-success"><i class="icon icon-ok"></i> <?= (isset($id)) ? "Salvar" : "Adicionar" ?>
					</div>
				</div>								
				
			</form>

			</div> <!-- /widget-content -->						
		</div> <!-- /widget -->	
		
	</div> <!-- span -->

</div> <!-- row -->