<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <title>Administração</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="<?= URL ?>css/adm/font-awesome.min.css">
  <link rel="stylesheet" href="<?= URL ?>css/adm/datatables.min.css">
  <link rel="stylesheet" href="<?= URL ?>css/adm/main.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">


  <!-- IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

</head>

  <body>
    <div class="menu-button">
      <i class="fa fa-bars"></i>  
    </div>
    <div class="side-menu">
      <div class="row logo-widget">
          <div class="logo">
            <div class="logo__img">
              <img src="<?= IMG ?>logo.png" alt="">
            </div> 
            <div class="logo__text">
              teste
            </div>
          </div>
      </div>
      
      <div class="row user-widget">
        <div class="user">
          <a href="<?=URL?>admin/edit/usuarios/<?= $_SESSION['dados_usuario']['id_developer']?>">
            <div class="user__img">
              <img src="<?= URL ?>files/<?= $_SESSION['dados_usuario']['imagem'] ?>" alt="">
            </div>
            
            <div class="user__name">
              <?= $_SESSION['dados_usuario']['nome']?>
            </div></a>
        </div>
      </div>

      <ul class="list">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon-user"></i>
            <span>Usuários</span>
            <b class="caret"></b>
          </a>

          <ul class="dropdown-menu sublist">
            <li><a href="<?= URL ?>admin/add/usuarios"><i class="icon-plus-sign"></i> Adicionar</a></li>
            <li><a href="<?= URL ?>admin/lista/usuarios"><i class="icon-list"></i> Listar</a></li>
          </ul>
        </li>

         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-envelope"></i>
            <span>Contatos</span>
            <b class="caret"></b>
          </a>

          <ul class="dropdown-menu sublist">
            <!-- <li><a href="<?= URL ?>admin/add/usuarios"><i class="icon-plus-sign"></i> Adicionar</a></li> -->
            <li><a href="<?= URL ?>admin/lista/contato"><i class="icon-list"></i> Listar</a></li>
          </ul>
        </li>

        <li>
          <a href="#">
            <i><img src="<?=IMG?>sair.png" alt=""></i>
           <a href="<?= URL?>admin/logout">Sair</a>
          </a>
        </li>

      </ul>

    </div>



    <div class="content">
      {conteudo}
    </div>

    
  </body>
    

<!-- Sessão de Javascript no final para loadar mais rápido -->


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script src="<?=URL?>js/admin.js"></script>
<script src="<?= URL ?>js/tinymce/tinymce.min.js"></script>
<script src="<?= URL ?>js/jquery.maskedinput.js"></script>
<script src="<?= URL ?>js/datatables.min.js"></script>



<script type="text/javascript">

  // TinyMCE
  tinymce.init({
        selector: "textarea",
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste jbimages"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link unlink image jbimages | fullscreen image preview | code",

        relative_urls: false
  });

  $('.data-table').DataTable({
        language: {
            search:         "Buscar:",
            lengthMenu:    "Exibir _MENU_ itens",
            info:           "Exibindo _START_ de _TOTAL_ itens",
            zeroRecords:    "Nenhum item encontrado",
            emptyTable:    "Nenhum item encontrado",
            paginate: {
                first:      "Primeira",
                previous:   "Anterior",
                next:       "Próxima",
                last:       "Última"
            },
        }
    });



  $(".cep").mask("99999-999");
  $(".cnpj").mask("99.999.999/9999-99");
  $("input[name*=telefone]").mask("(99) 9999-9999");
  $("input[name*=celular]").mask("(99) 99999-9999");


  // Função para perguntar sobre exclusão de item
  function del (id)
  {
    if(confirm('Tem certeza que deseja excluir?'))
      window.location.href = $("#" + id).attr("data");
  }

</script>

</body>
</html>
