<?
  $less = new lessc;  
  $less -> setFormatter('compressed');
  $less -> compileFile("css/less/less_style.less.css","css/style.css"); 
  $less -> compileFile("css/less/less_style_resp.less.css","css/style-responsive.css"); 
?>


<!doctype html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=en><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang=en><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9" lang=en><![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"><!--<![endif]-->    

    <head>		
		<title>Framework</title>
    
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        
        <!-- CSS -->
        <link rel="stylesheet" type="text/css" href="<?= CSS ?>style.css" />
        <link rel="stylesheet" type="text/css" href="<?= CSS ?>style-responsive.css" />


    </head>

    <body>  

    <div class="container">
      {conteudo}
    </div> 

    <!-- ################################ IMPORT SCRIPTS ############################### -->

    <!-- jQuery -->
    <script type="text/javascript" src="http://code.jquery.com/jquery.js"></script>
    
		<script type="text/javascript" src="<?= JS ?>bootstrap.min.js"></script>
		<script src="<?= JS ?>seletor.js"></script>

	</body>
	
</html>