<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <title>Administração</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="<?= URL ?>css/adm/adm-bootstrap.min.css">
  <link rel="stylesheet" href="<?= URL ?>css/adm/adm-bootstrap-fileupload.min.css">
  <link rel="stylesheet" href="<?= URL ?>css/adm/adm-bootstrap-responsive.min.css">
  <link rel="stylesheet" href="<?= URL ?>css/adm/font-awesome.min.css">

  <link href="<?= URL ?>css/adm/adm-style.css" rel="stylesheet" media="screen">
  <link href="<?= URL ?>css/adm/adm-style-responsive.css" rel="stylesheet" type="text/css">

  <!-- IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

</head>

  <body>
    <div class="container">
    
    {conteudo}

    </div>
  </body>
</html>
